# Week 4: In-Class Exercise - Data Filtering & Selection

## Objective
Practice filtering techniques using the same Education Statistics dataset you cleaned last week.

## Time: ~30 minutes

## What you'll practice:
1. **Single conditions** with comparison operators
2. **Combining conditions** with & (AND), | (OR), ~ (NOT)
3. **Convenience methods**: .isin(), .between(), .str.contains()
4. **Building real questions** from data

## Dataset
Same Education Statistics from the Colombian Ministry of Education (MEN) you cleaned in Week 3.

---

## Setup
Run this cell to load libraries, load the dataset, and apply the quick clean from Week 3.

In [1]:
import pandas as pd
import numpy as np

# Load the Education Statistics dataset
df = pd.read_csv('data/educacion_estadisticas.csv')

# Quick clean (applying what we learned in Week 3)
df['departamento'] = df['departamento'].str.upper().str.strip()
df['ano'] = df['ano'].fillna(0).astype(int)
df = df.drop_duplicates()
df = df.dropna(subset=['departamento'])

print(f"Dataset loaded and cleaned: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Years: {sorted(df['ano'].unique())}")
print(f"Departments: {df['departamento'].nunique()} unique")
df.head()

Dataset loaded and cleaned: 455 rows, 37 columns
Years: [np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Departments: 41 unique

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
1,2024,86,PUTUMAYO,81100,80.03,80.01,50.77,78.12,66.49,38.12,...,6.07,3.02,90.68,10.04,4.82,8.50,3.02,7.56,12.33,4.57
2,2016,52,NARIÑO,"394,574",71.10,NaN,38.56,68.32,56.56,29.80,...,1.89,0.04,97.71,3.07,1.92,2.64,0.04,2.36,3.79,1.34
3,2024,50,META,221911,90.34,90.29,65.69,89.17,76.00,48.10,...,6.84,2.85,91.18,11.36,5.61,9.27,2.85,9.27,12.53,3.49
4,2020,5,ANTIOQUIA,1151149,93.59,93.43,70.25,88.26,83.38,47.45,...,NaN,0.79,92.19,11.46,7.12,6.48,0.79,5.92,9.37,3.17

---

## Part 1: Single Conditions (8 minutes)

Start with simple, one-condition filters using comparison operators.

### Task 1.1: Filter by exact value
Get all rows where the year (`ano`) is 2023.

**Pattern:** `df[df['column'] == value]`

Print how many rows you found.

In [11]:
# YOUR CODE HERE
# Step 1: Create the filter
filtro_2023 = df[df['ano'] == 2023]

# Step 2: Print the number of rows
print("Número de filas:", len(filtro_2023))

# Step 3: Display the first few rows
filtro_2023.head()

Número de filas: 33

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
7,2023,73,TOLIMA,239730,99.13,99.04,76.38,98.24,83.94,54.77,...,6.47,4.21,91.72,10.13,5.28,8.61,4.21,9.19,10.89,3.31
15,2023,94,GUAINÍA,16704,71.61,71.55,62.35,70.20,36.75,10.67,...,NaN,5.96,80.41,14.54,7.97,15.69,5.96,19.12,14.73,5.24
39,2023,25,CUNDINAMARCA,sin dato,93.59,93.32,62.91,88.71,85.25,56.55,...,6.61,4.09,92.79,11.05,5.40,8.29,4.09,7.09,12.23,3.58
50,2023,99,VICHADA,33816,67.63,67.63,51.88,75.84,29.65,11.24,...,14.59,0.68,75.32,12.80,6.05,17.37,0.68,22.77,11.74,5.29

### Task 1.2: Filter with greater than
Find all rows where the total dropout rate (`desercion`) is greater than 5%.

**Question:** How many department-year combinations have a dropout rate above 5%?

In [8]:
filtro_desercion = df[df['desercion'] > 5]

print("Cantidad:", filtro_desercion.shape[0])
filtro_desercion.head()

Cantidad: 92

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
1,2024,86,PUTUMAYO,81100,80.03,80.01,50.77,78.12,66.49,38.12,...,6.07,3.02,90.68,10.04,4.82,8.50,3.02,7.56,12.33,4.57
9,2017,94,GUAINÍA,11965,80.00,79.98,59.60,78.83,36.62,8.82,...,15.53,7.92,78.42,19.29,13.37,3.13,7.92,3.35,3.28,0.38
13,2020,86,PUTUMAYO,"80,810",84.42,84.41,50.72,80.58,73.07,39.50,...,5.78,0.25,90.59,9.57,6.14,6.81,0.25,5.74,10.17,4.66
15,2023,94,GUAINÍA,16704,71.61,71.55,62.35,70.20,36.75,10.67,...,NaN,5.96,80.41,14.54,7.97,15.69,5.96,19.12,14.73,5.24
17,2011,95,GUAVIARE,31133,64.04,64.02,32.16,65.42,45.16,20.08,...,0.18,0.00,91.73,0.00,2.17,2.41,0.00,2.08,3.50,1.86

### Task 1.3: Filter with less than
Find all rows where net coverage (`cobertura_neta`) is less than 70%.

**Question:** Which departments have the lowest coverage? Look at the `departamento` column in your result.

In [10]:
filtro_cobertura = df[df['cobertura_neta'] < 70]

filtro_cobertura[['departamento', 'cobertura_neta']].head()

   departamento  cobertura_neta
17     GUAVIARE           64.02
23      VICHADA           68.25
33        HUILA           -9.26
43       VAUPÉS           53.45
45     GUAVIARE           59.18

---

## Part 2: Combining Conditions (8 minutes)

Now combine multiple conditions using `&` (AND), `|` (OR), and `~` (NOT).

**Remember:** Always wrap each condition in parentheses!

### Task 2.1: AND condition
Find rows where the year is 2023 AND the dropout rate is above 5%.

**Pattern:** `df[(condition1) & (condition2)]`

**Question:** Which departments had high dropout in 2023?

In [12]:
filtro_and = df[(df['ano'] == 2023) & (df['desercion'] > 5)]

filtro_and[['departamento', 'ano', 'desercion']]

        departamento   ano  desercion
15           GUAINÍA  2023       6.03
112         AMAZONAS  2023       5.01
150          CAQUETÁ  2023       6.89
383  VALLE DEL CAUCA  2023       5.22
384        RISARALDA  2023       5.60
408         GUAVIARE  2023       5.62

### Task 2.2: OR condition
Find all rows from either Antioquia OR Valle del Cauca.

**Pattern:** `df[(condition1) | (condition2)]`

**Hint:** The department names should be uppercase (we cleaned them in setup).

In [13]:
filtro_or = df[
    (df['departamento'] == 'ANTIOQUIA') |
    (df['departamento'] == 'VALLE DEL CAUCA')
]

filtro_or.head()

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
4,2020,5,ANTIOQUIA,1151149,93.59,93.43,70.25,88.26,83.38,47.45,...,NaN,0.79,92.19,11.46,7.12,6.48,0.79,5.92,9.37,3.17
24,2012,5,ANTIOQUIA,1278686,92.79,92.65,73.20,92.65,74.84,43.50,...,3.95,0.20,93.05,5.55,4.02,1.93,0.20,1.67,2.95,1.10
34,2011,5,ANTIOQUIA,1288473,94.01,93.85,70.28,94.12,75.68,44.37,...,2.06,0.07,94.56,2.54,2.96,4.25,0.07,4.56,5.27,1.68
55,2024,5,ANTIOQUIA,1128314,90.02,89.85,68.83,87.32,77.04,52.81,...,7.27,1.90,91.58,11.75,5.80,9.26,1.90,8.78,13.31,4.19
91,2012,76,VALLE DEL CAUCA,894698,88.26,88.09,60.32,86.16,71.21,40.62,...,3.29,0.20,93.91,5.28,3.33,1.64,0.20,1.39,2.40,1.01

### Task 2.3: NOT condition
Get all rows EXCEPT those from the "NACIONAL" department (the national aggregate).

**Two ways to do this:**
- `df[df['departamento'] != 'NACIONAL']`
- `df[~(df['departamento'] == 'NACIONAL')]`

Try both and verify you get the same number of rows.

In [14]:
# YOUR CODE HERE
# Method 1: using !=

filtro_not = df[df['departamento'] != 'NACIONAL']

len(filtro_not)

# Method 2: using ~

filtro_not = df[~(df['departamento'] == 'NACIONAL')]

len(filtro_not)

# Compare the row counts
print("Row count using !=:", len(df[df['departamento'] != 'NACIONAL']))
print("Row count using ~:", len(filtro_not))

Row count using !=: 455
Row count using ~: 455

---

## Part 3: Convenience Methods (7 minutes)

Use `.isin()`, `.between()`, and `.str.contains()` to write cleaner filters.

### Task 3.1: .isin() - Match a list
Find all rows from the following departments: ANTIOQUIA, BOGOTA D.C., VALLE DEL CAUCA, CUNDINAMARCA.

**Pattern:** `df[df['column'].isin([list_of_values])]`

In [24]:
# YOUR CODE HERE
filtro_isin = df[df['departamento'].isin([
    'ANTIOQUIA',
    'BOGOTA D.C.',
    'VALLE DEL CAUCA',
    'CUNDINAMARCA'
])]

len(filtro_isin)

40

### Task 3.2: .between() - Numeric range
Find all rows where the approval rate (`aprobacion`) is between 90 and 100 (inclusive).

**Pattern:** `df[df['column'].between(low, high)]`

In [27]:
# YOUR CODE HERE

filtro_between = df[df['aprobacion'].between(90, 100)]

filtro_between.head()
len(filtro_between)

199

### Task 3.3: .str.contains() - Text pattern
Find all rows where the department name contains "SANTANDER".

**Pattern:** `df[df['column'].str.contains('text', na=False)]`

**Question:** Which departments match? (Hint: there should be more than one.)

In [20]:
# YOUR CODE HERE
# Print the unique department names in your result
filtro_contains = df[df['departamento'].str.contains('SANTANDER', na=False)]

filtro_contains['departamento'].unique()

<StringArray>
['SANTANDER', 'NORTE DE SANTANDER']
Length: 2, dtype: str

---

## Part 4: Real Questions (5 minutes)

Use everything you've learned to answer these questions about the data.

### Task 4.1: Complex filter
Find departments in 2023 where:
- Net coverage is above 80% AND
- Dropout rate is below 3%

These are the "high performing" departments. Show the department name, coverage, and dropout columns.

In [21]:
# YOUR CODE HERE
filtro = df[
    (df['ano'] == 2023) &
    (df['cobertura_neta'] > 80) &
    (df['desercion'] < 3)
]

filtro[['departamento', 'ano', 'cobertura_neta', 'desercion']].head()

     departamento   ano  cobertura_neta  desercion
51      ATLÁNTICO  2023           93.63       2.34
73   BOGOTÁ, D.C.  2023           92.40       2.82
276         CHOCÓ  2023           84.91       2.32
340        BOYACÁ  2023           91.92       2.43

### Task 4.2: Try .query()
Rewrite the filter from Task 4.1 using `.query()` instead of boolean indexing.

**Pattern:** `df.query('condition1 and condition2')`

Verify you get the same number of rows.

In [2]:
# YOUR CODE HERE
filtro_query = df.query(
    "ano == 2023 and cobertura_neta > 80 and desercion < 3"
)

len(filtro_query)

4

---

## Bonus: Design Your Own Filter (if time permits)

Think of a question you could ask about the education data. Write the filter to answer it.

Example questions:
- Which departments had improving dropout rates (2022 lower than 2020)?
- Which departments in the Llanos region (Arauca, Casanare, Meta, Vichada) have the best coverage?
- What was the range of approval rates in 2024?

In [3]:
# YOUR QUESTION: ¿Qué departamentos en el año 2023 tienen cobertura mayor a 85%?
# YOUR CODE HERE
bonus = df[
    (df['ano'] == 2023) &
    (df['cobertura_neta'] > 85)
]

print("Departamentos con cobertura mayor a 85 en 2023:")

print(bonus[['departamento', 'ano', 'cobertura_neta']])

Departamentos con cobertura mayor a 85 en 2023:
           departamento   ano  cobertura_neta
0             SANTANDER  2023           95.64
7                TOLIMA  2023           99.04
39         CUNDINAMARCA  2023           93.32
51            ATLÁNTICO  2023           93.63
73         BOGOTÁ, D.C.  2023           92.40
97            MAGDALENA  2023           95.08
104              NARIÑO  2023          108.88
121           ANTIOQUIA  2023           91.89
125               CESAR  2023           86.70
239             QUINDIO  2023           92.73
249               HUILA  2023           90.41
257            CASANARE  2023           92.79
259               SUCRE  2023           92.44
273             CÓRDOBA  2023           88.80
307             BOLÍVAR  2023           99.52
309          LA GUAJIRA  2023           98.91
340              BOYACÁ  2023           91.92
365                META  2023           92.37
384           RISARALDA  2023           95.61
457  NORTE DE SANTANDER  2023           91.11

---

## Summary

In this exercise you practiced:

1. **Single conditions** - `==`, `!=`, `>`, `<`, `>=`, `<=`
2. **Combining conditions** - `&` (AND), `|` (OR), `~` (NOT)
3. **Convenience methods** - `.isin()`, `.between()`, `.str.contains()`
4. **Clean syntax** - `.query()` as an alternative

Key rules:
- Use `&` `|` `~` (NOT `and` `or` `not`) for DataFrames
- Always wrap conditions in **parentheses**
- Add `na=False` to `.str.contains()`

**Next:** Complete the workshop notebook for more complex filtering scenarios and analysis.